export const LOGIN_INPUTS = "LOGIN_INPUTS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CABREQUEST_MODAL = " CABREQUEST_MODAL";

export const CAB_REQUESTINPUTS = "CAB_REQUESTINPUTS";

export const CAB_REQUEST = "CAB_REQUEST";

export const DSPLAY_CARD = "DSPLAY_CARD";

export const VIEW_REQUESTS = "VIEW_REQUESTS";

export const APPROVE_REJECT = "APPROVE_REJECT";

export const ADDCAB_INPUTS = "ADDCAB_INPUTS";

export const ADDCAB_SUCCESS = "ADDCAB_SUCCESS";

export const MASTER_CABDETAILS = "MASTER_CABDETAILS";

export const UPDATE_MASTERCABS = "UPDATE_MASTERCABS";

export const UPDATECAB_INPUTS = "UPDATECAB_INPUTS";

export const DELETE_CABSUCC = "DELETE_CABSUCC";

export const ASSIGNCAB_INPUTS = "ASSIGNCAB_INPUTS";

export const ASSIGNCAB_SUCC = "ASSIGNCAB_SUCC";

export const VIEWCAB_DETAILS = "VIEWCAB_DETAILS";
